#!/usr/bin/env bash
set -e
git_checkout ${PACKAGE_VERSION}-styled
# start
npx @yeutech/rollup-umd-scripts peer add "react-transition-group*ReactTransitionGroup"
npx @yeutech/rollup-umd-scripts peer add "@bootstrap-styled/v4*BootstrapStyled"
npx @yeutech/rollup-umd-scripts peer add "@bootstrap-styled/provider*BootstrapProvider"
npx @yeutech/rollup-umd-scripts peer add "bootstrap-styled*BootstrapStyled"
cat > src/index.js << EOL
/**
 * Code your first module here
 */
import React from 'react';
import PropTypes from 'prop-types';
import Dropdown from '@bootstrap-styled/v4/lib/Dropdown';

// eslint-disable-next-line react/prefer-stateless-function
export default class ReactDemo extends React.Component {
  static propTypes = {
    testProps: PropTypes.bool,
  }

  static defaultProps = {
    testProps: true,
  }

  render() {
    const { testProps, ...rest } = this.props;
    return (
      <Dropdown {...rest}>
        <div>
          Hello
          {testProps}
        </div>
      </Dropdown>
    );
  }
}
EOL
cat > src/tests/index.test.js << EOL
/**
 * Testing example
 */

import React from 'react';
import { shallow } from 'enzyme';
import ReactDemo from '../index';

describe('<ReactDemo />', () => {
  it('should render a <Dropdown /> tag', () => {
    const renderedComponent = shallow(<ReactDemo />);
    expect(renderedComponent.find('Dropdown').length).toBe(1);
  });
});
EOL

